apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace . }}
  labels:
    {{- include "chart-operator.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:{{ .Values.pod.port }}'
    service:
      helm:
        http:
          clientTimeout: '{{ .Values.helm.http.clientTimeout }}'
        kubernetes:
          waitTimeout: '{{ .Values.helm.kubernetes.waitTimeout }}'
        maxRollback: '{{ .Values.helm.maxRollback }}'
        tillerNamespace:  '{{ .Values.tiller.namespace }}'
      image:
        registry: '{{ .Values.image.registry }}'
      kubernetes:
        incluster: true
        watch:
          namespace: '{{ tpl .Values.resource.default.namespace . }}'
