{{- if .Values.kyvernoPolicyExceptions.enabled }}
  {{- if .Capabilities.APIVersions.Has "kyverno.io/v2alpha1/PolicyException" -}}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: {{ tpl .Values.resource.default.name  . }}-policy-exceptions
  namespace: {{ .Values.kyvernoPolicyExceptions.namespace | default (include .Values.resource.default.namespace .) }}
  labels:
    {{- include "chart-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
spec:
  exceptions:
  - policyName: disallow-host-ports
    ruleNames:
    - host-ports-none
    - autogen-host-ports-none
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces

  match:
    any:
    - resources:
        kinds:
        - Deployment
        - Pod
        namespaces:
        - {{ tpl .Values.resource.default.namespace . }}
        names:
        - {{ tpl .Values.resource.default.name  . }}*
  {{- end -}}
{{- end -}}
